#/var/lib/tomcat8/webapps/ROOT

version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: aws/check.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/restart.sh
      timeout: 300
      runas: root
