version: 0.2
phases:
  pre_build:
    commands:
    - echo Entering pre_build phase...
    - ls -lrt
  build:
    commands:
    - echo Entering build phase...
    - echo Build started on `date`
    - mvn clean package
    - ls -lrt
    - ls -lrt target/
  post_build:
    commands:
    - echo Entering post_build phase...
    - echo Build completed on `date`i
    - ls -lrt
    - ls -lrt target/
    - mv target/aws-beanstalk-example-1-0.0.1-SNAPSHOT.war target/ROOT.war
artifacts:
  files:
  - target/aws-beanstalk-example-1-0.0.1-SNAPSHOT.war
  - aws/appspec.yml
  discard-paths: yes